apiVersion: apps/v1
kind: Deployment
metadata:
  name: stedi-muffin-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stedi-muffin-dev
  template:
    metadata:
      labels:
        app: stedi-muffin-dev
    spec:
      containers:
        - name: stedi-muffin-dev
          image: gcr.io/cheese-empanadas/muffin-stedi-api
          env: 
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-muffin
                  key: REDIS_PASSWORD
            - name: REDIS_HOST
              value: "redis-stedi-prod"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
          ports: 
            - containerPort: 443
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 10
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: stedi-muffin-nodeport
spec:
  selector:
    app: stedi-muffin-dev
  type: NodePort
  ports:
  - port: 80
    targetPort: 4567
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: stedi-muffin-certificate
spec:
  domains:
    - caleblybbert.cit262.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stedi-muffin-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: stedi-caleb-public
    networking.gke.io/managed-certificates: stedi-muffin-certificate
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stedi-muffin-nodeport
            port:
              number: 80